language: node_js
node_js:
- '0.10'
install:
- npm install
script:
- npm test
env:
  global:
  - secure: rdRRKiD0Ndfcy66gFOJP/8FZhx9bVk1VDUnMnavyLMbOKKV2jH4qkoFlYqr73D/EDADL8QepsKdGc51VtYewED2Ki98KNv+CmoXPfURqj97mAH3HycV4soinqC46elEpcIbhoOL2skyBRv8F2VwRyWzQiHKTlXrkL4anxzfF0xyVAo07Sy010AOgCLHU+j+kg1VTSwKtUSHJY5zunX+oNDJVQTPGKtWJ4eODggLv4eSRI8+fu9Z/AA+tV5BBU1d7Ey3GY9TD0Ady4HMZmvGGIQ76M6ULb++cXlAOGLR9Vv4YeCS1TnhLoZQGEJ+UFRR1hpVF4m3ignhqSkJ5+lvpFQAAKg0gS0GwNseR2XFNGusLwyUazQRk7u00s808lJ5GutL+rLGM2eZCAZprwe2SMxrAW5GLm6u/YMZycxGyBA/ikP11X9v5Zx1m6bNRJdRmfRiPFD5Il+Q29i1DWVVawvjkrcRH9GPtNxES64jS0K7hU28DQYq2vgWEP5AY6Uwsz2bK0wEswfffk4VDFps73cx39EMRH3xP4PpIRxsGddfYejcBH+9rGH+eaHzpQ8Q3zNsn7muYjZXcVPIu6Pze5mUmsox++Kq2llTXTy/WJ6MeDv2E/6AE7ArXs61E1lKDb+vcciWRBuD9gy5SaFQ6RJ/3cn4QLCWXNw4TUabeYrE=
  - secure: RjI8HiaKzer4Fg08Lmt7SNcnYpctL+kqHIhRBXgYhq6cjU4YpyFYn2pplOPKHEBLBMsL44u0cvJ6XGPMpUy16rKRphID4CzE0w6rkI2MJaPt2uKV+0TpllYDHZEiOMnuFAphp0JfJgLVVqfEQhNaLddlmArG2b8++CGjsq6QPPN2SYupdvwLTL8S2nQ8+zlmcU2wcl5WjgfEe6jPAEyP5KMUw0E8XmTisWUq1xSuzi5895s6UJ6sSPHrTChRErUcXznWevu+EbgtKxCGgmcRv3Ex/64/tzgsEUI1AFKcpfwdkXD2YQU0ZKCGRVICi0sXSM1BJd9PQB1afZKoNW+Qky7+LbsEhS+1xO9rxu0Iv2h+Eq8BnrZHvH6dwFqc/0O+4jvUhJiuRLS9+wYm0JsSCdiOLkdOpYdKN72IYMwB64gCDL0//FCZtuubZj1knBIL3pt8gh84YKl1XCrVBfZ/Tw374D9t+nvsBeFAhrVi6DCUFSuzGEY+1/MiX3nbwLAewUX7ez7MRq2A4JYHS/hrmz+VId4spT6SJ/erjS9Abt9d4Rrp/Jp8/craqmdIYscVv7N+ske/bQaSMX7XY2ri/+HuSiKUITSTWhMM9xJS3oT5HNuevxMug/3bwpYqXulBf2ikaDIVGdl+NQSE4E4ItUOUDrGVFuCu0EjoAAKksjg=
sudo: false
